### ISSUE TITLE
Tri par ordre alphabétique de la liste des pays dans les paris bonus.

### ISSUE THREAD

**Issue by emericdeperetti** [clemh78/worldcup#1]
La liste s'affiche avec les pays dans l'ordre des matchs, il serait plus intuitif d'avoir un ordre alphabétique.

**Comment by Cclleemm** [comment]
Nous allons modifier l’ordre de tri pour améliorer l’ergonomie de notre application.
Merci pour votre retour.

**Comment by clemh78** [comment]
Réglé au sein de la version 1.0.0
#7
