### ISSUE TITLE
Saisi des scores avec curseurs + bug entier négatifs

### ISSUE THREAD

**Issue by tomtomdu73** [clemh78/worldcup#13]
[BUG] Il est possible d'entrer des nombres négatifs pour les scores
[ENHANCEMENT] Use type:integer for the score input box to be able to use cursor

**Comment by clemh78** [comment]
Réglé dans la version 1.0.2.

Champs html inchangés, changement d'une règle PHP pour bloquer les nombres négatifs.

#15
