### ISSUE TITLE
Impossible de modifier un pari sur iPhone X

### ISSUE THREAD

**Issue by Cclleemm** [clemh78/worldcup#9]
Lorsque l'on édite un pari sur iphone X (donc sur mobile en général je suppose) alors une double erreur est affichée. Il est donc impossible de modifier son pari

**Comment by clemh78** [comment]
Le bug est connu et un correctif est en cours de réalisation.

Ce bug concerne uniquement le navigateur SAFARI.

**Comment by Cclleemm** [comment]
Merci pour votre réactivité.

**Comment by clemh78** [comment]
Résolu dans la version 1.0.1.

#11
